name: Linting testing building
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  Build_project:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - name: build production project
        run: npm run build:prod
  Linting:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - name: linting typescript
        run: npm run lint:ts
      - name: linting scss
        run: npm run lint:scss
  Testing:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - name: unit tests
        run: npm run test:unit
  # Screenshot_testing:
  #   runs-on: windows-latest
  #   strategy:
  #     matrix:
  #       node-version: [20.x]
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Staring Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: ${{ matrix.node }}
  #     - run: npm install
  #     - name: build storybook
  #       run: npm run storybook:build
  #     - name: screenshot testing
  #       run: npm run test:ui:ci
