name: Linting testing building
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
  build_project:
    runs-on: ubuntu-latest
    needs: [install_dependencies]
    steps:
      - uses: actions/checkout@v4
      - name: build production project
        run: npm run build:prod
  Linting:
    runs-on: ubuntu-latest
    needs: [install_dependencies]
    steps:
      - uses: actions/checkout@v4
      - name: linting typescript
        run: npm run lint:ts
      - name: linting scss
        run: npm run lint:scss
  Testing:
    needs: [install_dependencies]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: unit tests
        run: npm run test:unit
